logging:
  path: /usr/log/xzs/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xzs?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Llx60717937